#!/usr/bin/env python3
"""End-to-end CNN showcase on REAL images: the same net, trained in Python and in Lean.

This script does the data plumbing and the comparison; the *learning logic* lives entirely
in `model.py` -- a single self-contained file that both CPython runs directly and PyAstLean
transpiles to Lean 4. There is no second copy of the network and nothing is hardcoded into
the model: the dataset is decoded here and streamed to both runtimes as plain floats on stdin.

Pipeline:

  1. Load real MNIST "0"/"1" digit PNGs (downloaded + cached by `fetch_data.py`).
  2. Downsample each to an 8x8 grayscale grid with PIL/numpy, normalise to [0, 1], and
     serialise the whole dataset as a flat list of floats (the stdin payload).
  3. Feed that payload to `model.py` two ways:
        - straight in CPython, and
        - transpiled to Lean 4 by PyAstLean (`src/py2lean.py`), compiled and executed with
          `lake env lean --run` -- reading the very same floats from stdin.
  4. Compare the two backends and render two visuals:
        - an ASCII report in the terminal (the 8x8 grid the net actually sees), and
        - `gallery.png`, a montage of the real digits annotated with truth / Python / Lean.

    source /home/anirudhgupta/PyAstLean/.venv/bin/activate
    python3 example_scripts/showcase/cnn/run_showcase.py
"""

import math
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import fetch_data  # noqa: E402

REPO_ROOT = HERE.parents[2]
PY2LEAN = REPO_ROOT / "src" / "py2lean.py"
MODEL_PY = HERE / "model.py"
MODEL_LEAN = HERE / "model.lean"      # generated by the transpiler
GALLERY = HERE / "gallery.png"

GRID = 8            # images are downsampled to GRID x GRID

SHADES = " .:-=+*#%@"   # intensity ramp for ASCII rendering
CLASS_NAME = {1: "one", 0: "zero"}


# --------------------------------------------------------------------------------------
# 1-2. Load the real PNGs, downsample to 8x8, and serialise to a stdin payload of floats.
# --------------------------------------------------------------------------------------
def load_dataset():
    """Return (images, labels, originals): images are 8x8 float grids in [0,1]; originals are
    the full-res PIL digit images (for the gallery)."""
    cache = fetch_data.load()
    images, labels, originals = [], [], []
    # Interleave the classes so the montage alternates 0, 1, 0, 1, ...
    for i in range(max(len(v) for v in cache.values())):
        for label in (0, 1):
            paths = cache.get(label, [])
            if i < len(paths):
                orig = Image.open(paths[i]).convert("L")
                small = orig.resize((GRID, GRID), Image.Resampling.BILINEAR)
                images.append(np.asarray(small, dtype=float) / 255.0)
                labels.append(label)
                originals.append(orig)
    return images, labels, originals


def build_stdin(images, labels):
    """Serialise the dataset the way `model.py` reads it: image count, then per image the
    label followed by 64 row-major pixel floats -- one value per line."""
    lines = [str(len(images))]
    for img, label in zip(images, labels):
        lines.append(str(label))
        for r in range(GRID):
            for c in range(GRID):
                lines.append(f"{float(img[r][c]):.4f}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------------------
# 3. Run model.py in Python and (via PyAstLean -> Lean) in Lean, both fed the same stdin.
# --------------------------------------------------------------------------------------
def run_python(payload):
    proc = subprocess.run([sys.executable, str(MODEL_PY)], input=payload,
                          capture_output=True, text=True, cwd=REPO_ROOT)
    if proc.returncode != 0:
        raise RuntimeError(f"Python run failed:\n{proc.stderr}")
    return proc.stdout


def transpile_to_lean():
    proc = subprocess.run(
        [sys.executable, str(PY2LEAN), str(MODEL_PY), "--target", "command"],
        capture_output=True, text=True, cwd=REPO_ROOT)
    if proc.returncode != 0 or not proc.stdout.strip():
        raise RuntimeError(f"Transpilation failed:\n{proc.stderr or proc.stdout}")
    MODEL_LEAN.write_text(proc.stdout)


def run_lean(payload):
    proc = subprocess.run(["lake", "env", "lean", "--run", str(MODEL_LEAN)], input=payload,
                          capture_output=True, text=True, cwd=REPO_ROOT)
    if proc.returncode != 0:
        raise RuntimeError(f"Lean run failed:\n{proc.stderr or proc.stdout}")
    return proc.stdout   # predictions on stdout; linter warnings on stderr


def parse_predictions(output):
    preds, acc = {}, None
    for line in output.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] == "pred":
            preds[int(parts[1])] = int(parts[2])
        elif len(parts) == 3 and parts[0] == "accuracy":
            acc = (int(parts[1]), int(parts[2]))
    return preds, acc

def report(images, labels, py_preds, lean_preds, py_acc, lean_acc):
    bar = "=" * 78
    print(bar)
    print("  PyAstLean CNN showcase  --  one network, trained in Python AND in Lean")
    print(bar)
    print(f"  data    : {len(images)} real MNIST digits (0 vs 1), downsampled to {GRID}x{GRID}")
    print("  model   : 2x2 conv -> ReLU -> dense(49->1) -> sigmoid, 250 epochs SGD")
    print("  bridge  : pixels decoded in Python, streamed to both runtimes as stdin floats")
    print(bar)

    agree = 0
    for n in range(len(images)):
        truth = CLASS_NAME[labels[n]]
        pyp, lnp = py_preds.get(n), lean_preds.get(n)
        same = (pyp == lnp)
        agree += int(same)
        print()
        print(f"  digit #{n:<2} truth: {truth:<5}"
              f"  python: {CLASS_NAME.get(pyp, '?'):<5}"
              f"  lean: {CLASS_NAME.get(lnp, '?'):<5}"
              f"  {'== match' if same else '!! DIFFER'}")

    print()
    print(bar)
    pa = f"{py_acc[0]}/{py_acc[1]}" if py_acc else "?"
    la = f"{lean_acc[0]}/{lean_acc[1]}" if lean_acc else "?"
    print(f"  accuracy   python: {pa}     lean: {la}")
    print(f"  agreement  python vs lean: {agree}/{len(images)} predictions identical")
    verdict = ("PERFECT -- the transpiled Lean network behaves exactly like the Python one."
               if agree == len(images) and py_acc == lean_acc
               else "MISMATCH -- see the rows marked !! DIFFER above.")
    print(f"  verdict    {verdict}")
    print(bar)
    print(f"  saved visual montage -> {GALLERY}")


# --------------------------------------------------------------------------------------
# 4b. Image visual: a montage of the real digits annotated with predictions.
# --------------------------------------------------------------------------------------
def _font(size):
    for name in ("DejaVuSans-Bold.ttf", "DejaVuSans.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def save_gallery(originals, labels, py_preds, lean_preds, py_acc, lean_acc):
    img_px, pad, text_h = 96, 16, 46
    cell_w = img_px + 40
    cell_h = img_px + text_h + pad
    title_h = 88

    # Pick a column count that keeps the montage roughly square rather than a tall strip.
    count = len(originals)
    cols = max(4, min(count, round(math.sqrt(count * cell_h / cell_w))))
    rows = (count + cols - 1) // cols

    f_title, f_sub, f_cell = _font(24), _font(15), _font(15)
    title = "PyAstLean CNN  -  Python vs Lean on real MNIST digits"

    bg = (18, 18, 24)
    probe = ImageDraw.Draw(Image.new("RGB", (10, 10)))
    title_w = int(probe.textlength(title, font=f_title))
    W = max(cols * cell_w + pad, title_w + 2 * pad)
    H = title_h + rows * cell_h + pad

    canvas = Image.new("RGB", (W, H), bg)
    draw = ImageDraw.Draw(canvas)
    draw.text((pad, 16), title, font=f_title, fill=(235, 235, 245))

    pa = f"{py_acc[0]}/{py_acc[1]}" if py_acc else "?"
    la = f"{lean_acc[0]}/{lean_acc[1]}" if lean_acc else "?"
    agree = sum(int(py_preds.get(n) == lean_preds.get(n)) for n in range(len(originals)))
    draw.text((pad, 54),
              f"accuracy  python {pa}   lean {la}        agreement  {agree}/{len(originals)} identical",
              font=f_sub, fill=(150, 200, 255))

    ok_col, bad_col, diff_col = (70, 200, 120), (220, 80, 80), (230, 190, 70)
    for n, orig in enumerate(originals):
        r, c = divmod(n, cols)
        x0 = pad + c * cell_w
        y0 = title_h + r * cell_h

        pyp, lnp = py_preds.get(n), lean_preds.get(n)
        if pyp != lnp:
            border = diff_col
        elif pyp == labels[n]:
            border = ok_col
        else:
            border = bad_col

        thumb = orig.resize((img_px, img_px), Image.Resampling.NEAREST).convert("RGB")
        canvas.paste(thumb, (x0, y0))
        draw.rectangle([x0, y0, x0 + img_px - 1, y0 + img_px - 1], outline=border, width=3)

        ty = y0 + img_px + 4
        draw.text((x0, ty), f"truth {labels[n]}", font=f_cell, fill=(200, 200, 210))
        draw.text((x0, ty + 18), f"py {pyp}   ln {lnp}", font=f_cell, fill=border)

    canvas.save(GALLERY)


# --------------------------------------------------------------------------------------
def main():
    images, labels, originals = load_dataset()
    payload = build_stdin(images, labels)

    print("[1/3] running the network in Python ...", file=sys.stderr)
    py_out = run_python(payload)

    print("[2/3] transpiling the network to Lean 4 with PyAstLean ...", file=sys.stderr)
    transpile_to_lean()

    print("[3/3] compiling & running the Lean network (lake env lean --run) ...",
          file=sys.stderr)
    lean_out = run_lean(payload)

    py_preds, py_acc = parse_predictions(py_out)
    lean_preds, lean_acc = parse_predictions(lean_out)

    save_gallery(originals, labels, py_preds, lean_preds, py_acc, lean_acc)
    report(images, labels, py_preds, lean_preds, py_acc, lean_acc)


if __name__ == "__main__":
    main()
