name = "PyAstLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PyAstLean", "py2lean"]
testDriver = "PyAstLeanTest"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "PyAstLean"

[[lean_lib]]
name = "Libraries"

[[lean_lib]]
name = "PyAstLeanTest"

[[lean_exe]]
name="py2lean"
supportInterpreter = true

[[lean_exe]]
name="palc"
supportInterpreter = true
